[package]
name = "oriole-text-dev"
version = "0.1.0"
authors = ["johannesvollmer <johannes.boenki@t-online.de>"]
edition = "2018"

[dependencies]
oriole-text = { path = "../oriole-text" }

# when used, these are dev-dependencies
rusttype = "0.7.5"
signed-distance-field = "0.6.3"
resize = "0.3.0"
rect_packer = "0.2.1"