[package]
name = "oriole-text-dev"
version = "0.1.0"
authors = ["johannesvollmer <johannes.boenki@t-online.de>"]
edition = "2018"

[dependencies]
# core
rusttype = "0.7.5"
rect_packer = "0.2.1"
signed-distance-field = "0.6.2"

# serialization
compress = "0.1.2"
serde = "1.0.87"
bincode = "1.1.1"
serde_derive = "1.0.87"

# alternatives to std
hashbrown = "0.1.8"